# Generated by Django 3.2.16 on 2022-11-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='user@user.user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
