# Generated by Django 3.2.16 on 2022-11-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0002_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('questions', models.CharField(max_length=1024)),
                ('date', models.DateField(default=None, null=True)),
                ('groups', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
