# Generated by Django 3.2.16 on 2022-11-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0003_auto_20221125_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
