# Generated by Django 3.2.16 on 2022-11-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0004_alter_quiz_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
    ]
