# Generated by Django 3.2.16 on 2022-11-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='scheduleId',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
