# Generated by Django 3.2.16 on 2022-11-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0006_person_scheduleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='api_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='scheduleId',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
    ]
