# Generated by Django 3.2.16 on 2022-11-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0007_auto_20221126_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='scheduleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAS.group'),
        ),
    ]
