# Generated by Django 3.2.16 on 2022-11-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0009_attendance_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checkIn',
        ),
    ]
