# Generated by Django 3.2.16 on 2022-11-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0010_remove_attendance_checkin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture')},
        ),
    ]
