# Generated by Django 3.2.16 on 2022-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0013_myscchedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myscchedule',
            name='sched',
            field=models.CharField(max_length=1024),
        ),
    ]
