# Generated by Django 3.2.16 on 2022-11-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0014_alter_myscchedule_sched'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyScchedule',
            new_name='MySchedule',
        ),
    ]
