# Generated by Django 3.2.16 on 2022-11-27 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0015_rename_myscchedule_myschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('leccture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAS.lecture')),
            ],
        ),
    ]
