# Generated by Django 3.2.16 on 2022-11-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0016_anonquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonquestion',
            name='leccture',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
