# Generated by Django 3.2.16 on 2022-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0017_alter_anonquestion_leccture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lectorSSID',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
